config/routes.rb
Rails.application.routes.draw do
  get 'is_on_sell/index'
  get 'favorites/update'
  get 'favorites/index'
  get 'messages/index'
  get 'conversations/index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",:registrations => 'users/registrations' }
  devise_scope :user do
    get "users/profile"=> "users/registrations#profile", :as => "profile_registration"
  end
  devise_scope :product do
    get "products/isonsell"=> "products/isonsell", :as => "isonsell_product"
    get "products/markassell"=> "products/markassell", :as => "markassell_product"
    get "products/sellingnow"=> "products/sellingnow", :as => "sellingnow_product"
    get "products/reactive"=> "products/reactive", :as => "reactive_product"
    end
  #resources :products
  resources :charges
  resources :products do
    collection do
      get :search
    end
  end  

  root 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :user
    searchkick word_start: [:pname, :pdescription]
    has_many_attached :images

    def search_data
      {
        pname: pname,
        pdescription: pdescription
      }
    end

    
      
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [ :show, :index]
  # GET /products
  # GET /products.json
  def index
    @products = Product.search "*", page: params[:page], per_page: 5
    if user_signed_in?
    @users = User.where.not(id: current_user.id)
    @favorite_exists = Favorite.where(product: @product, user: current_user) == [] ? false : true
    end
  end
  # GET /products/1
  # GET /products/1.json
  def show
    if user_signed_in?
      @users = User.where.not(id: current_user.id)
      @favorite_exists = Favorite.where(product: @product, user: current_user) == [] ? false : true
    end
  end

  def sellingnow
    @users = User.all
    @product = Product.where(isonsell: false , user_id: current_user)
  end

  def isonsell
    @users = User.all
    @product = Product.where(isonsell: true , user_id: current_user)
  end

  def reactive
    @product = Product.find(params[:id])
    @product.update_attribute(:isonsell, @product.isonsell = true)
    @counter=current_user.psellingcount+1
    @counter2=current_user.psoldedcount-1
    current_user.update_attribute(:psellingcount, current_user.psellingcount = @counter )
    current_user.update_attribute(:psoldedcount, current_user.psoldedcount = @counter2 )  
    respond_to do |format|
      if @product.save
        format.html { redirect_to sellingnow_product_path, notice: 'Ürün tekrar aktif edildi' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def markassell
      @product = Product.find(params[:id])
      @product.update_attribute(:isonsell, @product.isonsell = false)
      @counter=current_user.psoldedcount+1
      @counter2=current_user.psellingcount-1
      current_user.update_attribute(:psoldedcount, current_user.psoldedcount = @counter)
      current_user.update_attribute(:psellingcount, current_user.psellingcount = @counter2)
      respond_to do |format|
        if @product.save
          format.html { redirect_to isonsell_product_path, notice: 'Ürün satıldı olarak değiştirildi.' }
          format.json { render :show, status: :created, location: @product }
        else
          format.html { render :new }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
  end
  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    attributes = product_params.merge(user_id: current_user.id)
    @product = Product.new(attributes)
    @counter=current_user.psellingcount+1
    current_user.update_attribute(:psellingcount, current_user.psellingcount = @counter)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Ürün güncellendi.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    if current_user.psellingcount > 0
      @counter=current_user.psellingcount-1
      current_user.update_attribute(:psellingcount, current_user.psellingcount = @counter)
    end
    if current_user.psoldedcount > 0
      @counter2=current_user.psoldedcount-1
      current_user.update_attribute(:psoldedcount, current_user.psoldedcount = @counter2)
    end
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @term = params[:term].to_s
    @result = Product.search(@term)
    @products = @result
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:pname, :pdescription, :pprice, :plocation, :photo,:isonsell, :user_id, images: [])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pname %>
    <%= form.text_field :pname %>
  </div>

  <div class="field">
    <%= form.label :pdescription %>
    <%= form.text_field :pdescription %>
  </div>

  <div class="field">
    <%= form.label :pprice %>
    <%= form.number_field :pprice %>
  </div>

  <div class="field">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<% if user_signed_in? %>
  <div class="container">
    <div class="row">
    <div class="col-xs-12 col-md-6">
    <div class="bd-example">
  <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="https://www.w3schools.com/images/picture.jpg" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5>First slide label</h5>
          <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
    </div>

    <div class="col-xs-12 col-md-6">
      <div class="product-edit">
      <%= form_with model: @product, :html => { :multipart => true } do |form| %>
            <p>
                <%= form.label :"Ürün Başlığı:" %>
                <%= form.text_field :pname ,:class=>"autocomplete form-control", :required => true%>
                
            </p>
            <p>
                <%= form.label :"Ürün Açıklama:" %>
                <%= form.text_area :pdescription,:class=>"autocomplete form-control", :required => true, :rows => 4 %>
                
            </p>
            <p>
                <%= form.label :"Ürün Fiyatı:" %>
                <span id="product-price-lab"><%= form.number_field :pprice ,:id=>"product-price-label",:class=>"autocomplete form-control", :required => true%>
                <img id="turkish-coin-icon" src="https://image.flaticon.com/icons/svg/12/12037.svg" width="25" height="25" alt="Turkish Lira free icon" title="Turkish Lira free icon">
                </span>
                
            </p>
             <p>
                <%= form.file_field :photo, :required => true %>
            </p>
            <div class="btn-group" role="group" aria-label="Basic example">
               <%= button_tag 'submit', :class=> "btn btn-success" do %>
                 <i class="fas fa-save" style="font-size: 32px;"></i>
               <% end %>
                <%= link_to @product, :class=>"btn btn-success" do %>
                  <i class="fas fa-eye" style="font-size: 32px;"></i>
                <% end %>
                <%= link_to products_path, :class=>"btn btn-success" do %>
                  <i class="fas fa-arrow-alt-circle-left" style="font-size: 32px;"></i>
                <% end %>
                </div>
      <% end %>
      </div>
     </div>
    </div>
  </div>
 <% else %>
   <p>Hello World</p>
   <% end %>

app/views/products/index.html.erb
<%= content_tag(:div, content_tag(:p), class: "favori-alert", id:'favorite_link', remote: true) %>
<div class="products">
			<div class="container">
				<div class="row">
					<div class="col-lg-6 offset-lg-3">
						<div class="section_title text-center">Popular on Little Closet</div>
					</div>
				</div>
				<div class="row page_nav_row">
					<div class="col">
						<div class="page_nav">
							<ul class="d-flex flex-row align-items-start justify-content-center">
								<li class="active"><a href="category.html">Women</a></li>
								<li><a href="category.html">Men</a></li>
								<li><a href="category.html">Kids</a></li>
								<li><a href="category.html">Home Deco</a></li>
							</ul>
						</div>
					</div>
				</div>
				<div class="row products_row">
				<% @products.each do |product| %>
          <% if product.isonsell == true%>
					<div class="col-xl-4 col-md-6">
						<div class="product">
							<div class="product_image"><%= link_to(image_tag(product.images[0].variant(resize: "1920x1080")), product_path(product)) %>
							</div>
							<div class="product_content">
								<div class="product_info d-flex flex-row align-items-start justify-content-start">
									<div>
										<div>
											<div class="product_name_product"><a href="product.html"><%= product.pname %></a></div>
											<div class="product_category"><%= product.pdescription %></div>
										</div>
									</div>
									<div class="ml-auto text-right">
										<div class="rating_r rating_r_4 home_item_rating"><i></i><i></i><i></i><i></i><i></i></div>
										<div class="product_price_product text-right"><%= product.pprice %><img id="turkish-coin-icon" src="https://image.flaticon.com/icons/svg/12/12037.svg" width="15" height="25" alt="Turkish Lira free icon" title="Turkish Lira free icon"></div>
									</div>
								</div>
								<div class="product_buttons">
									<div class="text-right d-flex flex-row align-items-start justify-content-start">
										<div class="product_button product_fav text-center d-flex flex-column align-items-center justify-content-center">
											<div><div>
												<% if user_signed_in? %>
													<% @users.each do |user| %>
														<% if user.id == product.user_id %>
															<%= link_to conversations_path(sender_id: current_user.id, receiver_id:user.id), method: :post do %>
															<i class="fas fa-comments" style="font-size: 32px;"></i>
															<% end %>
														<% end %>
													<% end %>
													<% if current_user.id == product.user_id %>
													<%= link_to "javascript:messageInfo()" do %>
														<i class="fas fa-comments" style="font-size: 32px;"></i>
													<% end %>	
													<% end %>
												<% end %>
											</div></div>
										</div>
                    <div class="product_button product_fav text-center d-flex flex-column align-items-center justify-content-center">
											<div><div><%= content_tag(:a,:'class' => 'pop',:'id' => 'pop', :'data-toggle' => 'popover',
											:'data-content' => content_tag(:input,nil,readonly: true, id: "link-input",
											:value => ('http://localhost:3000/'+product_path(product.id)))+('<button id="share-copy-button" class="btn btn-primary" onclick="copyToClipboard()">Kopyala</button>')) do %>
												<i class="fas fa-share-square" style="font-size: 32px;"></i>
											<%end%></div></div>
										</div>
										<div class="product_button product_cart text-center d-flex flex-column align-items-center justify-content-center">
											<div><div> 
											<% if user_signed_in? %>
											<% if current_user.id != product.user_id%>
											<%= link_to favorites_update_path(product: product), remote: true do %>
												<i class="fas fa-heart" style="font-size: 32px;"></i>
											<% end %>
											<% else %>
											<%= link_to "javascript:favInfo()" do %>
												<i class="fas fa-heart" style="font-size: 32px;"></i>
											<% end %>	
											<% end %>
											<% end %>
											</div></div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
          <% end %>
        <% end %>
				</div>
				<div class="row load_more_row">
					<div class="col">
						<%= paginate @products %>
					</div>
				</div>
			</div>
		</div>

app/views/products/isonsell.html.erb
<div class="isonsell">
<div class="container">
<div id="edit-row" class="row">
  <div class="col-lg-4 col-md-5 col-sm-4">
    <div class="list-group">
    <span class="list-group-item list-group-item-success"><%=current_user.username%></span>
    <a href="" class="list-group-item bg-secondary disabled">Satışta Olanlar<span class="badge badge-warning float-right"><%= current_user.psellingcount %></span></a>
    <a href="/products/sellingnow" class="list-group-item">Satılanlar<span class="badge badge-warning float-right"><%= current_user.psoldedcount %></span></a>
    <% @users.each do |user| %>
     <% if user.id == current_user.id%>
       <%= link_to favorites_index_path , :class=>"list-group-item" do %>
      Favorilerim
      <span class="badge badge-warning float-right"><%= current_user.pfavoritescount %></span>
     <% end %>
    <%= link_to 'Mesajlar', conversations_path(sender_id: current_user.id, receiver_id: user.id), method: :post , :class=>"list-group-item" %>
  <% end %>
   <% end %>
    <a href="/users/edit" class="list-group-item">Üyeliğimi Güncelle</a>
  </div>
  </div>
  <% @product.each do |p| %>
  <% if p.isonsell == true %>
    <div class="col-lg-4 col-md-7 col-sm-8">
    <div class="card" style="width: 18rem;">
   <%= link_to(image_tag(p.images[0].variant(resize: "1920x1080"), :class=>"img-slider"), p) %>
  <div class="card-body">
    <h5 class="card-title"><%= p.pname%></h5>
    <p class="card-text"><%= p.pdescription%></p>
    <%= link_to "Satıldı olarak işaretle", {:controller => "products", :action => "markassell", :id => p.id}, :class=>"btn btn-warning" %>
  </div>
</div>
</div> 
  <% end %> 
   <% end %>
   </div> 
   </div> 
</div> 

app/views/products/new.html.erb
  <div class="products">
  <div class="container">
    <div class="row">
    <div class="col-xs-12 col-md-6">
      <div class="product-edit">
      <%= form_with model: @product, :html => { :multipart => true } do |form| %>
            <p>
                <%= form.label :"Ürün Başlığı:" %>
                <%= form.text_field :pname ,:class=>"autocomplete form-control", :required => true%>
                
            </p>
            <p>
                <%= form.label :"Ürün Açıklama:" %>
                <%= form.text_area :pdescription,:class=>"autocomplete form-control", :required => true, :rows => 4 %>
                
            </p>
            <p>
                <%= form.label :"Ürün Fiyatı:" %>
                <span id="product-price-lab"><%= form.number_field :pprice ,:id=>"product-price-label",:class=>"autocomplete form-control", :required => true%>
                <img id="turkish-coin-icon" src="https://image.flaticon.com/icons/svg/12/12037.svg" width="25" height="25" alt="Turkish Lira free icon" title="Turkish Lira free icon">
                </span>              
            </p>
             <p>
                 <%= form.file_field :images, multiple: true, :required => true %>
            </p>
             <div class="btn-group" role="group" aria-label="Basic example">
        <%= button_tag 'submit', :class=> "btn btn-success" do %>
          <i class="fas fa-save" style="font-size: 32px;"></i>
        <% end %>
        <%= link_to products_path, :class=>"btn btn-success" do %>
          <i class="fas fa-arrow-alt-circle-left" style="font-size: 32px;"></i>
        <% end %>
      </div>
      <% end %>
      </div>
     </div>
    </div>
  </div> 
   </div> 

app/views/products/search.html.erb
<div class = "search">
<div class = "container">
    <div class = "row-product">
    <h1>Elastic search for products</h1>
    <% unless @products.nil? %>
    <% if @products.empty? %>
        <h2>No products found matching your query.</h2>
    <% else %>
        <h2>Search results</h2>

        <table style="width: 100%;">
        <thead>
            <tr>
            <th>Author</th>
            <th>Title</th>
            <th>Tags</th>
            <th>Published on</th>
            <th>Actions</th>
            </tr>
        </thead>

        <tbody>
            <% @products.each do |product| %>
            <tr>
                <td><%= product.pname %></td>
                <td><%= product.pdescription %></td>
                <td><%= product.pprice %></td>
                <td><%= link_to 'View', product_path(product.id) %></td>
                <td><%= image_tag product.images[0].variant(resize: "1920x1080") %> </td>
            </tr>
            <% end %>
        <tbody>
        </table>
    <% end %>
    <% end %>
    </div>
</div>
</div>

app/views/products/sellingnow.html.erb
<div class="solded">
<div class="container">
<div id="edit-row" class="row">
  <div class="col-lg-4 col-md-5 col-sm-4">
    <div class="list-group">
    <span class="list-group-item list-group-item-success"><%=current_user.username%></span>
    <a href="/products/isonsell" class="list-group-item">Satışta Olanlar<span class="badge badge-warning float-right"><%= current_user.psellingcount %></span></a>
    <a href="" class="list-group-item bg-secondary disabled">Satılanlar <span class="badge badge-warning float-right"><%= current_user.psoldedcount %></span></a>
    <% @users.each do |user| %>
     <% if user.id == current_user.id%>
       <%= link_to favorites_index_path , :class=>"list-group-item" do %>
      Favorilerim
      <span class="badge badge-warning float-right"><%= current_user.pfavoritescount %></span>
     <% end %>
    <%= link_to 'Mesajlar', conversations_path(sender_id: current_user.id, receiver_id: user.id), method: :post , :class=>"list-group-item" %>
  <% end %>
   <% end %>
    <a href="/users/edit" class="list-group-item">Üyeliğimi Güncelle</a>
  </div>
  </div>
  <% @product.each do |p| %>
  <% if p.isonsell == false %>
    <div class="col-lg-4 col-md-7 col-sm-8">
    <div class="card" style="width: 18rem;">
   <%= link_to(image_tag(p.images[0].variant(resize: "1920x1080"), :class=>"img-slider"), p) %>
  <div class="card-body">
    <h5 class="card-title"><%= p.pname%></h5>
    <p class="card-text"><%= p.pdescription%></p>
    <%= link_to "Tekrar sat", {:controller => "products", :action => "reactive", :id => p.id}, :class=>"btn btn-warning" %>
  </div>
</div>
</div> 
  <% end %> 
   <% end %>
   </div> 
   </div> 
</div> 