config/routes.rb
Rails.application.routes.draw do
  get 'is_on_sell/index'
  get 'favorites/update'
  get 'favorites/index'
  get 'messages/index'
  get 'conversations/index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",:registrations => 'users/registrations' }
  devise_scope :user do
    get "users/profile"=> "users/registrations#profile", :as => "profile_registration"
  end
  devise_scope :product do
    get "products/isonsell"=> "products/isonsell", :as => "isonsell_product"
    get "products/markassell"=> "products/markassell", :as => "markassell_product"
    get "products/sellingnow"=> "products/sellingnow", :as => "sellingnow_product"
    get "products/reactive"=> "products/reactive", :as => "reactive_product"
    end
  #resources :products
  resources :charges
  resources :products do
    collection do
      get :search
    end
  end  

  root 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alyadasat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/445e609dfd.js" crossorigin="anonymous"></script>
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
  </head>

  <body>
  <nav id="navbar" class="navbar navbar-expand-lg navbar-dark" style="background-color: #211D1D;">
    <a class="navbar-brand" href="/"><img class="home-logo" src="/assets/navbar/logo-home.png"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item">
          <%= form_for :term, url: search_products_path,:html => {:class => 'header-search-form'}, method: :get do |form| %>
							<%= text_field_tag :term, params[:term],
								placeholder: "istediğin ürün burada eminim",
								autocomplete: :off,
								autocorrect: :off,
								autocapitalize: :off %>
							<%= submit_tag "Ara", class: 'hide' %>
							<% end %>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
                  <span id="product-sell-button"><%= link_to 'Ürün Sat', new_product_path, :class=>"btn btn-outline-warning my-2 my-sm-0" %></span>
              <% if user_signed_in? %>
                <%= link_to 'Çıkış Yap', destroy_user_session_path,:class=>"btn btn-outline-success my-2 my-sm-0", method: :delete %>
                <%= link_to image_tag(current_user.avatar.url(:thumb), border: 0,:class=>"avatar"), profile_registration_path ,:class=>"avatar" %>
              <% else %>
                <%= link_to 'Giriş Yap', new_user_session_path,:class=>"btn btn-outline-success my-2 my-sm-0" %>
                <%= link_to 'Kayıt Ol', new_user_registration_path,:class=>"btn btn-outline-success my-2 my-sm-0" %>
              <% end %>  
      </form>
    </div>
</nav>

      <%if notice %><div class="alert alert-info"><%= notice %></div><% end %>
      <%if alert %><div class="alert alert-warning"><%= alert %></div><% end %>
    <%= yield %>
  </body>
</html>